name: Build and Deploy Backend

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'

jobs:
  build-and-deploy-backend:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: "prince0127"
          password: "Docker@27."
          # SECURITY WARNING: It is highly recommended to use secrets for passwords!
          # password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker image
        run: |
          cd backend
          docker build -t prince0127/backend-app:latest .

      - name: Push Backend Docker image
        run: |
          docker push prince0127/backend-app:latest

      - name: Stop and remove old backend container (if exists)
        run: |
          if [ "$(docker ps -aq -f name=backend-container)" ]; then
            docker stop backend-container
            docker rm backend-container
          fi

      - name: Run Backend Docker container
        run: |
          docker run -d --name backend-container -p 8000:8000 prince0127/backend-app:latest
